# Generated by Django 2.0 on 2021-02-12 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_act', models.CharField(max_length=50)),
                ('prenom_act', models.CharField(max_length=50)),
                ('telephone_act', models.CharField(max_length=50)),
                ('num_ide_act', models.CharField(max_length=50)),
                ('etat_act', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Acteur',
            },
        ),
        migrations.CreateModel(
            name='Acteur_groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_act_group', models.CharField(max_length=50)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Acteur')),
            ],
            options={
                'db_table': 'Acteur_groupe',
            },
        ),
        migrations.CreateModel(
            name='Colline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_col', models.CharField(max_length=50)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Acteur')),
            ],
            options={
                'db_table': 'Colline',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_com', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Commune',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_mes', models.TextField()),
                ('date_mes', models.DateField(auto_now_add=True)),
                ('heure_mes', models.TimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Acteur')),
            ],
            options={
                'db_table': 'Reponse',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_mes', models.TextField()),
                ('date_mes', models.DateField(auto_now_add=True)),
                ('heure_mes', models.TimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Acteur')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_uti', models.CharField(max_length=50)),
                ('prenom_uti', models.CharField(max_length=50)),
                ('num_id_uti', models.CharField(max_length=50)),
                ('telephone_uti', models.CharField(max_length=50)),
                ('profil_act', models.CharField(max_length=50)),
                ('etat_act', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
        migrations.AddField(
            model_name='reponse',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Utilisateur'),
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Province'),
        ),
        migrations.AddField(
            model_name='colline',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Commune'),
        ),
        migrations.AddField(
            model_name='acteur_groupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Groupe'),
        ),
    ]
