# Generated by Django 2.0 on 2021-02-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0002_auto_20210212_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='etat_act',
            new_name='etat',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='profil_act',
            new_name='profil',
        ),
    ]
