# Generated by Django 2.0 on 2021-02-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0003_auto_20210215_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='telephone_uti',
        ),
    ]
