# Generated by Django 2.0 on 2021-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0004_remove_utilisateur_telephone_uti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='date_mes',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='heure_mes',
            field=models.TimeField(),
        ),
    ]
