# Generated by Django 2.0 on 2021-02-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0006_remove_utilisateur_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='categories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Categorie'),
        ),
    ]
