# Generated by Django 2.0 on 2021-02-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0007_auto_20210225_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_nyaruka.Categorie'),
        ),
    ]
