# Generated by Django 2.0 on 2021-02-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0008_auto_20210225_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur_groupe',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Acteur'),
        ),
        migrations.AlterField(
            model_name='acteur_groupe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Groupe'),
        ),
        migrations.AlterField(
            model_name='colline',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Acteur'),
        ),
        migrations.AlterField(
            model_name='colline',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Commune'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Acteur'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Utilisateur'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='acteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Acteur'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Categorie'),
        ),
    ]
