# Generated by Django 2.0 on 2021-02-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0009_auto_20210226_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='colline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Colline'),
            preserve_default=False,
        ),
    ]
