# Generated by Django 2.0 on 2021-04-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0011_prise_charge_victime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='prise_charge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_nyaruka.Prise_charge'),
        ),
    ]
