# Generated by Django 2.0 on 2021-04-03 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_nyaruka', '0012_reports_prise_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='victime',
            name='date_evenement',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
